name: C CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ansible-lint
    - uses: ansible/ansible-lint-action@v4.1.0.post0
    - name: make
      run: make
