name: C CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Server
      shell: bash
      run: gcc -w -pthread -o Server Server.c 
    - name: Client
      shell: bash
      run: gcc -w -o Client Client.c
      
      
      
